### ISSUE TITLE
Memory allocation not released

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityMobilePaint#10]
> I have run into a problem. Whenever I call upon the paint scene it increases the memory with 2.5-2.6 MB! This increase NEVER disappears, it only happens once, but it’s still annoying. I tried running System.GC.Collect() and Resources.UnloadUnusedAssets(). So what is causing this increase and how do I dispose of it?

**Comment by unitycoder** [comment]
Can you post screenshot of profiler / memory sample window? (does it happen in editor only?)

**Comment by martinmaxk** [comment]
Don't know why you want screenshots, the only reason I can think of is that you don't trust me, but here they are:

The focus point is the text at the top all the way to the right it says (x MB) that's the memory dump.

Before:

![skaermbillede 2015-12-09 14 59 34](https://cloud.githubusercontent.com/assets/16225943/11687895/ae6250ee-9e89-11e5-8adb-c299be663814.png)

After:
![skaermbillede 2015-12-09 14 59 43](https://cloud.githubusercontent.com/assets/16225943/11687910/c1298936-9e89-11e5-85aa-7c0b0a3bc83c.png)

Profiler:
![skaermbillede 2015-12-09 14 59 46](https://cloud.githubusercontent.com/assets/16225943/11687926/c99b6422-9e89-11e5-8e9c-9467fdfec446.png)

**Comment by martinmaxk** [comment]
Oh yeah by the way forgot to include the memory part of the profiler.

![skaermbillede 2015-12-09 15 49 36](https://cloud.githubusercontent.com/assets/16225943/11688384/944d1f74-9e8c-11e5-992d-3a5b7621f2b9.png)

**Comment by martinmaxk** [comment]
I can also confirm that the increase has something to do with the MobilePaint script.

**Comment by martinmaxk** [comment]
I figured it out. Whenever you create a new byte array the memory heap goes up. But how to deallocate that memory again, hmm...

**Comment by martinmaxk** [comment]
The GC should take care of the byte arrays when the scene is destroyed and the value of the byte arrays are null, but I guess for some reason they linger on between scenes, maybe there's a reference to them in an object that isn't deleted in between?

**Comment by martinmaxk** [comment]
Discovered how to fix this some time ago. I bet it could be done more effectively (iterate over all public and private byte[] variables), but this works for me. Just assign the byte arrays to null and you're good to go. You don't have to explicitly call the GC, but I did it anyways to make it more instant. Place it in MobilePaint script and when the object is deleted, it's cleaned too. 

I'm only using these two byte arrays.
BTW if you find out how to do this more effectively like I described, could you send me the code? Thanks.

void OnDestroy()
        {
            undoPixels = null;
            pixels = null;
            System.GC.Collect();
            Debug.Log(System.GC.GetTotalMemory(false));
        }

**Comment by unitycoder** [comment]
nice, that solution seems fine, no other ideas right now.

unity gc>
http://docs.unity3d.com/Manual/UnderstandingAutomaticMemoryManagement.html

**Comment by unitycoder** [comment]
added OnDestroy() cleaning up to v1.96
