### ISSUE TITLE
Saving/Loading canvas texture, wrong size?

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityMobilePaint#12]
>  any news on saving the canvastexture and reloading it as a canvastexture? I'm trying to get it to work but it doesn't save the image as the size it was suppose to save it? When reloading the texture onto the canvas it's not fullscreen (the original is) it's missing a part of the left side. 
> http://forum.unity3d.com/threads/released-mobile-paint-with-multi-touch.262645/page-4#post-2445924

**Comment by TripwireNL** [comment]
This seems to be fixed. I tried it out and it's working perfectly fine now :)

**Comment by unitycoder** [comment]
No new reports on this, so closing the issue for now..
