### ISSUE TITLE
Changing resolution (for example rotating screen) breaks things

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityMobilePaint#3]
Because Screen.width is used on some parts of the code (values are taken before resize, and they are not updated on resize)

**Comment by unitycoder** [comment]
current workaround is to not allow resize or rotation.. (or reload scene after screen resize)

**Comment by BelieveXiaoShuai** [comment]
I am using this plugin to develop VR application, and i have this problem ,too. When I grab the quad(Paint Board) to move, I could not paint or paint line in chaos.

**Comment by unitycoder** [comment]
could try replacing anything with Screen.width and Screen.height, with your own fixed resolution

**Comment by BelieveXiaoShuai** [comment]
![image](https://user-images.githubusercontent.com/26036057/69405398-89d62b00-0d3a-11ea-94f6-a5e679e2c1c8.png)
What is wrong with it？

**Comment by unitycoder** [comment]
test disabling [x] connect lines or so, cant remember right now what was that issue, maybe in forum thread had something about it..

**Comment by BelieveXiaoShuai** [comment]
I find RaycastHitInfo.textureCoor is Vector2.zero sometimes.May be because of it. i disable connect lines and only could paint point instead of line.

**Comment by BelieveXiaoShuai** [comment]
I solved it. something with same layer upon it.

**Comment by unitycoder** [comment]
ok. yes, if raycast hits something else that could happen.
