### ISSUE TITLE
Unsupported on Unity 2019.3

### ISSUE THREAD

**Issue by wagenheimer** [unitycoder/UnityMobilePaint#40]
GuiTexture does not exist anymore in Unity 2019.3.

Is there some update planned to make it compatible?

**Comment by unitycoder** [comment]
yeah, old GUI stuff and GUItextures should be replaced with new UI, Canvas images/rawimages..
(currently no free time to do updates, but if anyone is interested to add pull requests, ill merge them in)

**Comment by unitycoder** [comment]
actually all those guitexture scripts are not used anymore, removed those scripts
