### ISSUE TITLE
How to use Mask or RectMask2d to cover MobilePaintBoard? Like UGUI Scroll View?

### ISSUE THREAD

**Issue by BelieveXiaoShuai** [unitycoder/UnityMobilePaint#44]
When i put paint board into Scroll View, Mask could not cover paint board. When I scroll out paint board, I still could see paint board.

**Comment by unitycoder** [comment]
i'm thinking the UI masks require shader that supports masking (with stencils).. so it could be that.
no idea if taking the masking code from ui shaders would fix it..
