### ISSUE TITLE
License is missing

### ISSUE THREAD

**Issue by QuentinBrun** [unitycoder/UnityMobilePaint#55]
Hi,

You have written that this 'asset' is free, it is not available anymore on asset store. Could you release it under one license by adding the license file ?

I would like to use it in a free app, but I cannot if there is no licenses.

Thanks!

**Comment by unitycoder** [comment]
can be used on free and commercial apps, but would be nice if sources are not (re) sold as is, like an asset store plugin.
not sure whats the best license for that?
but you are safe to use for that use case certainly.

**Comment by QuentinBrun** [comment]
Thanks for your quick answer. I will probably not use it if there is no 'standard' license publication (like MIT or Apache v2) but I understand your fears and I do not know of any licenses to ensure that sources cannot be sold as is.

**Comment by QuentinBrun** [comment]
Hi just to let you know, I will use another lib to comply with the law. But I may have a license that would be good for you, it is MPL: https://www.mozilla.org/en-US/MPL/ . In this case, someone can use your lib in free and commercial app. He will also be able to sell the source as is on the asset store but he will have to state that he is using your lib and that the code source is available under MPL with a link to download the source. In this case nobody would buy him the code...

**Comment by unitycoder** [comment]
i think MIT is also fine then, saw this type of MIT + comment on not selling in store.. sounds ok for me:
https://github.com/JustInvoke/Randomation-Vehicle-Physics#license-info
