### ISSUE TITLE
Multiple undos

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityMobilePaint#7]
Currently only 1 undo step is possible, because all drawing is applied to the texture directly. More undo steps would require saving multiple copies of the whole texture (or atleast parts of it)

**Comment by fad12** [comment]
have u manage to figure this out cuz im trying to solve it with no luck

**Comment by unitycoder** [comment]
I have one version using that list of buffers.. havent tried on mobile, i can email you this version if want to try..?
![mobile_paint_multiple_undos](https://cloud.githubusercontent.com/assets/5438317/11614862/d8c9c3a0-9c57-11e5-8def-ef063d487d8a.gif)

**Comment by fad12** [comment]
that will be awesome I can test it on different devices

**Comment by unitycoder** [comment]
sent.

**Comment by fad12** [comment]
i tested it on : 
- iphone 5 ios 8.4.1  it works great with 60 fps 
- ipad air 2 ios 8.4.1 it works great with 60 fps
- samsung nexus s Android 4.1.1 (worst case scenario) laggy 
- samsung tab A android 5.0.1 laggy but somehow acceptable

note : for android i'm not so sure it is lagging cuz of undo or some stuff need to be optimized in my code

**Comment by unitycoder** [comment]
On androids it does get slow if you use full screen resolution, like 2048×1536, that is huge texture to update.. (using resolution scaler like 0.5 or 0.25 helps alot, then can add post effect to camera for extra antialias to smoothen it)

i'm looking into adding option to split canvas to smaller pieces which should fix it,
but makes flood fills, patterns paints etc. bit difficult to handle..

**Comment by fad12** [comment]
one thing I'm trying to make the user get list of the colors he used to color his room walls i can just record the selected colors but if the user erased the color then it should not be in the list do u have i a way to do it without effect the performance and read the pixels colors again.

**Comment by unitycoder** [comment]
multiple undos, using list of undo buffer arrays is in v1.96

**Comment by ChambersChiu** [comment]
can you send me multi undo to me ?

**Comment by unitycoder** [comment]
its available in the asset store (v1.96)
