### ISSUE TITLE
List of used colors in drawing

### ISSUE THREAD

**Issue by unitycoder** [unitycoder/UnityMobilePaint#9]
> one thing I'm trying to make the user get list of the colors he used to color his room walls i can just record the selected colors but if the user erased the color then it should not be in the list do u have i a way to do it without effect the performance and read the pixels colors again https://github.com/unitycoder/UnityMobilePaint/issues/7#issuecomment-162855836

iterating through all the colors in pixels[] array should be ok (not too slow),
so could use that to collect which colors are used in drawing.. i can test it also.

**Comment by fad12** [comment]
i did a test but the results was too slow for the mobile

**Comment by unitycoder** [comment]
do you need to get the list only once at save? or more often? (could also skip every 2nd or 3rd pixel, probably not necessary to calculate small single pixels)

**Comment by fad12** [comment]
it could be more then one time

**Comment by fad12** [comment]
ok skipping some pixels was a good idea it worked well now thank u so much

**Comment by unitycoder** [comment]
closing this, probably could try doing the calculation in another thread also..but might get complicated.
